// Generated by tools/make-sw.mjs — do not edit by hand.
const VERSION = 'starquest-d53d0a3664';
const SHELL = [
  "./",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-1024.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "manifest.webmanifest",
  "src/core/math.js",
  "src/game/ai.js",
  "src/game/boarding.js",
  "src/game/data.js",
  "src/game/player.js",
  "src/game/ship.js",
  "src/game/station.js",
  "src/game/tutorial.js",
  "src/game/world.js",
  "src/main.js",
  "src/render/backend.js",
  "src/render/lines.js",
  "src/render/models.js",
  "src/render/palette.js",
  "src/render/renderer.js",
  "src/render/renderer_gl.js",
  "src/render/scene.js",
  "src/render/shaders.js",
  "src/render/shaders_gl.js",
  "src/ui/audio.js",
  "src/ui/hud.js",
  "src/ui/input.js",
  "src/ui/mobile.js",
  "src/ui/screens.js",
  "src/ui/style.css"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache first — the game must run with no signal at all — then refresh in the
// background so the next launch picks up a new build.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(caches.match(req).then((hit) => {
    const net = fetch(req).then((res) => {
      if (res && res.ok) caches.open(VERSION).then((c) => c.put(req, res.clone()));
      return res;
    }).catch(() => hit);
    return hit || net;
  }));
});
