// Rebuilds sw.js with the current app-shell file list and a content hash,
// so a deploy always invalidates the old cache. Run: node tools/make-sw.mjs
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const walk = (dir, out = []) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
};

const files = [
  'index.html', 'manifest.webmanifest',
  ...walk(join(ROOT, 'src')).map((p) => relative(ROOT, p)),
  ...walk(join(ROOT, 'icons')).map((p) => relative(ROOT, p)),
].filter((f) => /\.(html|js|css|png|webmanifest)$/.test(f)).sort();

const hash = createHash('sha1');
for (const f of files) hash.update(readFileSync(join(ROOT, f)));
const version = hash.digest('hex').slice(0, 10);

writeFileSync(join(ROOT, 'sw.js'), `// Generated by tools/make-sw.mjs — do not edit by hand.
const VERSION = 'starquest-${version}';
const SHELL = ${JSON.stringify(['./', ...files], null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache first — the game must run with no signal at all — then refresh in the
// background so the next launch picks up a new build.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(caches.match(req).then((hit) => {
    const net = fetch(req).then((res) => {
      if (res && res.ok) caches.open(VERSION).then((c) => c.put(req, res.clone()));
      return res;
    }).catch(() => hit);
    return hit || net;
  }));
});
`);
console.log(`sw.js -> ${version}, ${files.length + 1} entries`);
